### ISSUE TITLE
Same content being logged twice

### ISSUE THREAD

**Issue by phsantiago32** [ThiagoBarradas/restsharp-serilog-auto#2]
### Status

BUG REPORT 

### Steps

1.  Send any request via RestClientAutolog.
2. Check logged request and response contents.

### Expected behaviour

The program should log both request and response separately, with it's respective properties.

### Actual behaviour

The program logs the same message twice, with the same properties and message template.

**Comment by ThiagoBarradas** [comment]
Hey Guy! Thank you for contact me about this issue.

In version `1.0.11` this bug was fixed.

:)

Please, update package in your project.
