### ISSUE TITLE
Update default variables in README

### ISSUE THREAD

**Issue by millsaj** [ThiagoBarradas/restsharp-serilog-auto#6]
The default variables listed in the README are out of date. 

For example `Uri` should be `Url` and `Body` should be `RequestBody`.

In the meantime the real list of variables can be found [here](https://github.com/ThiagoBarradas/restsharp-serilog-auto/blob/80b3e78f605ae9cb76bcc8a336885e9040052dcc/RestSharp.Serilog.Auto/RestClientAutolog.cs#L178).

**Comment by ThiagoBarradas** [comment]
Thx @millsaj! ;)
