### ISSUE TITLE
Brings in lots of unnecessary dependencies

### ISSUE THREAD

**Issue by xantari** [ThiagoBarradas/restsharp-serilog-auto#8]
Task: Remove PackUtils and JsonMasking.

These two libraries bring in about 60 unnecessary packages into a full framework project, things like dozens of Swashbuckle assemblies, Snappy.NET, Multiple MongoDB packages, about 30 Microsoft.AspnetCore.* packages.

Application went from 27 files at 12.5MB to 106 files at around 35 MB!

Packages.config BEFORE and AFTER:

![image](https://user-images.githubusercontent.com/6610039/95665161-47b10600-0b13-11eb-9f1b-33da7b72849a.png)

**Comment by ThiagoBarradas** [comment]
Hello Guy! Sorry about delay! I will do this and release a new version in a few days! Thanks!
